import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// ✅ 5. 병렬 라우트: @slot (루트 레벨)
// app/layout.tsx
// export default function RootLayout({ children, nav }: { children: React.ReactNode; nav: React.ReactNode }) {
//     return (
//         /*<div style={{ display: 'flex', gap: '1rem' }}>
//             <aside style={{ width: '220px', background: '#eef1f4', padding: '1rem' }}>{nav}</aside>
//             <main style={{ flex: 1 }}>{children}</main>
//         </div>*/
//         <html lang="ko">
//         <body>
//         <div style={{ display: 'flex', gap: '1rem' }}>
//             <aside>{nav}</aside>
//             <main style={{ flex: 1 }}>{children}</main>
//         </div>
//         </body>
//         </html>
//     );
// }

export default function RootLayout({ children, nav }: { children: React.ReactNode; nav: React.ReactNode }) {
    return (
        /*<div style={{ display: 'flex', gap: '1rem' }}>
            <aside style={{ width: '220px', background: '#eef1f4', padding: '1rem' }}>{nav}</aside>
            <main style={{ flex: 1 }}>{children}</main>
        </div>*/
        <html lang="ko">
        <body>
        <div style={{ display: 'flex', gap: '1rem' }}>
            <aside>{nav}</aside>
            <main style={{ flex: 1 }}>{children}</main>
        </div>
        </body>
        </html>
    );
}
// export default function RootLayout({ children }: { children: React.ReactNode }) {
//     return (
//         /*<div style={{ display: 'flex', gap: '1rem' }}>
//             <aside style={{ width: '220px', background: '#eef1f4', padding: '1rem' }}>{nav}</aside>
//             <main style={{ flex: 1 }}>{children}</main>
//         </div>*/
//         <html lang="ko">
//         <body>
//         <div style={{ display: 'flex', gap: '1rem' }}>
//             <main style={{ flex: 1 }}>{children}</main>
//         </div>
//         </body>
//         </html>
//     );
// }

